name: game_grid
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.0.1
  cloud_functions: ^6.0.1
  country_picker: ^2.0.27
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  expandable: ^5.0.1
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  firebase_database: ^12.0.1
  flutter:
    sdk: flutter
  flutter_advanced_switch: ^3.1.0
  flutter_slidable: ^4.0.1
  flutter_svg: ^2.2.0
  flutter_xlider: ^3.5.0
  get: ^4.7.2
  logger: ^2.6.1
  percent_indicator: ^4.2.5
  pinput: ^5.0.1
  smooth_page_indicator: ^1.2.1
  syncfusion_flutter_charts: ^30.2.7
  syncfusion_flutter_gauges: ^30.2.7

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/satoshi/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/satoshi/Satoshi-Regular.otf
          weight: 400
        - asset: assets/fonts/satoshi/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/satoshi/Satoshi-Bold.otf
          weight: 700
        - asset: assets/fonts/satoshi/Satoshi-Black.otf
          weight: 900

flutter_assets:
  assets_path: assets/
  output_path: lib/constants/
  filename: app_images.dart
  field_prefix: ""
