// To parse this JSON data, do
//
//     final todaysMatchesModel = todaysMatchesModelFromJson(jsonString);

import 'dart:convert';

TodaysMatchesModel todaysMatchesModelFromJson(String str) => TodaysMatchesModel.fromJson(json.decode(str));

String todaysMatchesModelToJson(TodaysMatchesModel data) => json.encode(data.toJson());

class TodaysMatchesModel {
    bool success;
    Pager pager;
    Metadata metadata;
    List<Datum> data;
    String message;

    TodaysMatchesModel({
        required this.success,
        required this.pager,
        required this.metadata,
        required this.data,
        required this.message,
    });

    factory TodaysMatchesModel.fromJson(Map<String, dynamic> json) => TodaysMatchesModel(
        success: json["success"],
        pager: Pager.fromJson(json["pager"]),
        metadata: Metadata.fromJson(json["metadata"]),
        data: List<Datum>.from(json["data"].map((x) => Datum.fromJson(x))),
        message: json["message"],
    );

    Map<String, dynamic> toJson() => {
        "success": success,
        "pager": pager.toJson(),
        "metadata": metadata.toJson(),
        "data": List<dynamic>.from(data.map((x) => x.toJson())),
        "message": message,
    };
}

class Datum {
    int id;
    int homeId;
    int awayId;
    String season;
    Status status;
    int roundId;
    int gameWeek;
    int revisedGameWeek;
    Goals homeGoals;
    Goals awayGoals;
    int homeGoalCount;
    int awayGoalCount;
    int totalGoalCount;
    int teamACorners;
    int teamBCorners;
    int totalCornerCount;
    int teamAOffsides;
    int teamBOffsides;
    int teamAYellowCards;
    int teamBYellowCards;
    int teamARedCards;
    int teamBRedCards;
    int teamAShotsOnTarget;
    int teamBShotsOnTarget;
    int teamAShotsOffTarget;
    int teamBShotsOffTarget;
    int teamAShots;
    int teamBShots;
    int teamAFouls;
    int teamBFouls;
    int teamAPossession;
    int teamBPossession;
    dynamic refereeId;
    int coachAId;
    int coachBId;
    String stadiumName;
    String stadiumLocation;
    int teamACardsNum;
    int teamBCardsNum;
    double oddsFt1;
    double oddsFtX;
    double oddsFt2;
    double oddsFtOver05;
    double oddsFtOver15;
    double oddsFtOver25;
    double oddsFtOver35;
    double oddsFtOver45;
    double oddsFtUnder05;
    double oddsFtUnder15;
    double oddsFtUnder25;
    double oddsFtUnder35;
    double oddsFtUnder45;
    double oddsBttsYes;
    double oddsBttsNo;
    double oddsTeamACsYes;
    double oddsTeamACsNo;
    double oddsTeamBCsYes;
    double oddsTeamBCsNo;
    double oddsDoublechance1X;
    double oddsDoublechance12;
    double oddsDoublechanceX2;
    double odds1StHalfResult1;
    double odds1StHalfResultX;
    double odds1StHalfResult2;
    double odds2NdHalfResult1;
    double odds2NdHalfResultX;
    double odds2NdHalfResult2;
    double oddsDnb1;
    double oddsDnb2;
    double oddsCornersOver75;
    double oddsCornersOver85;
    double oddsCornersOver95;
    double oddsCornersOver105;
    double oddsCornersOver115;
    double oddsCornersUnder75;
    double oddsCornersUnder85;
    double oddsCornersUnder95;
    double oddsCornersUnder105;
    double oddsCornersUnder115;
    double oddsCorners1;
    double oddsCornersX;
    double oddsCorners2;
    double oddsTeamToScoreFirst1;
    double oddsTeamToScoreFirstX;
    double oddsTeamToScoreFirst2;
    double oddsWinToNil1;
    double oddsWinToNil2;
    double odds1StHalfOver05;
    double odds1StHalfOver15;
    double odds1StHalfOver25;
    double odds1StHalfOver35;
    double odds1StHalfUnder05;
    double odds1StHalfUnder15;
    double odds1StHalfUnder25;
    double odds1StHalfUnder35;
    double odds2NdHalfOver05;
    double odds2NdHalfOver15;
    double odds2NdHalfOver25;
    double odds2NdHalfOver35;
    double odds2NdHalfUnder05;
    double odds2NdHalfUnder15;
    double odds2NdHalfUnder25;
    double odds2NdHalfUnder35;
    int oddsBtts1StHalfYes;
    int oddsBtts1StHalfNo;
    int oddsBtts2NdHalfYes;
    int oddsBtts2NdHalfNo;
    int overallGoalCount;
    int htGoalsTeamA;
    int htGoalsTeamB;
    int goals2HgTeamA;
    int goals2HgTeamB;
    int goalCount2Hg;
    int htGoalCount;
    int dateUnix;
    int winningTeam;
    int noHomeAway;
    int bttsPotential;
    int bttsFhgPotential;
    int btts2HgPotential;
    int goalTimingDisabled;
    int attendance;
    int cornerTimingsRecorded;
    int cardTimingsRecorded;
    int teamAFhCorners;
    int teamBFhCorners;
    int teamA2HCorners;
    int teamB2HCorners;
    int cornerFhCount;
    int corner2HCount;
    int teamAFhCards;
    int teamBFhCards;
    int teamA2HCards;
    int teamB2HCards;
    int totalFhCards;
    int total2HCards;
    int attacksRecorded;
    int teamADangerousAttacks;
    int teamBDangerousAttacks;
    int teamAAttacks;
    int teamBAttacks;
    int teamAXg;
    int teamBXg;
    int totalXg;
    int teamAPenaltiesWon;
    int teamBPenaltiesWon;
    int teamAPenaltyGoals;
    int teamBPenaltyGoals;
    int teamAPenaltyMissed;
    int teamBPenaltyMissed;
    int pensRecorded;
    int goalTimingsRecorded;
    int teamA010MinGoals;
    int teamB010MinGoals;
    int teamACorners010Min;
    int teamBCorners010Min;
    int teamACards010Min;
    int teamBCards010Min;
    int throwinsRecorded;
    int teamAThrowins;
    int teamBThrowins;
    int freekicksRecorded;
    int teamAFreekicks;
    int teamBFreekicks;
    int goalkicksRecorded;
    int teamAGoalkicks;
    int teamBGoalkicks;
    int o45Potential;
    int o35Potential;
    int o25Potential;
    int o15Potential;
    int o05Potential;
    int o15HtPotential;
    int o05HtPotential;
    int o052HPotential;
    int o152HPotential;
    double cornersPotential;
    double offsidesPotential;
    double cardsPotential;
    double avgPotential;
    String homeUrl;
    String homeImage;
    String homeName;
    String awayUrl;
    String awayImage;
    String awayName;
    double homePpg;
    double awayPpg;
    double preMatchHomePpg;
    double preMatchAwayPpg;
    double preMatchTeamAOverallPpg;
    double preMatchTeamBOverallPpg;
    int u45Potential;
    int u35Potential;
    int u25Potential;
    int u15Potential;
    int u05Potential;
    int cornersO85Potential;
    int cornersO95Potential;
    int cornersO105Potential;
    double teamAXgPrematch;
    double teamBXgPrematch;
    double totalXgPrematch;
    String matchUrl;
    int competitionId;
    int matchesCompletedMinimum;
    List<dynamic> homeGoalsTimings;
    List<dynamic> awayGoalsTimings;

    Datum({
        required this.id,
        required this.homeId,
        required this.awayId,
        required this.season,
        required this.status,
        required this.roundId,
        required this.gameWeek,
        required this.revisedGameWeek,
        required this.homeGoals,
        required this.awayGoals,
        required this.homeGoalCount,
        required this.awayGoalCount,
        required this.totalGoalCount,
        required this.teamACorners,
        required this.teamBCorners,
        required this.totalCornerCount,
        required this.teamAOffsides,
        required this.teamBOffsides,
        required this.teamAYellowCards,
        required this.teamBYellowCards,
        required this.teamARedCards,
        required this.teamBRedCards,
        required this.teamAShotsOnTarget,
        required this.teamBShotsOnTarget,
        required this.teamAShotsOffTarget,
        required this.teamBShotsOffTarget,
        required this.teamAShots,
        required this.teamBShots,
        required this.teamAFouls,
        required this.teamBFouls,
        required this.teamAPossession,
        required this.teamBPossession,
        required this.refereeId,
        required this.coachAId,
        required this.coachBId,
        required this.stadiumName,
        required this.stadiumLocation,
        required this.teamACardsNum,
        required this.teamBCardsNum,
        required this.oddsFt1,
        required this.oddsFtX,
        required this.oddsFt2,
        required this.oddsFtOver05,
        required this.oddsFtOver15,
        required this.oddsFtOver25,
        required this.oddsFtOver35,
        required this.oddsFtOver45,
        required this.oddsFtUnder05,
        required this.oddsFtUnder15,
        required this.oddsFtUnder25,
        required this.oddsFtUnder35,
        required this.oddsFtUnder45,
        required this.oddsBttsYes,
        required this.oddsBttsNo,
        required this.oddsTeamACsYes,
        required this.oddsTeamACsNo,
        required this.oddsTeamBCsYes,
        required this.oddsTeamBCsNo,
        required this.oddsDoublechance1X,
        required this.oddsDoublechance12,
        required this.oddsDoublechanceX2,
        required this.odds1StHalfResult1,
        required this.odds1StHalfResultX,
        required this.odds1StHalfResult2,
        required this.odds2NdHalfResult1,
        required this.odds2NdHalfResultX,
        required this.odds2NdHalfResult2,
        required this.oddsDnb1,
        required this.oddsDnb2,
        required this.oddsCornersOver75,
        required this.oddsCornersOver85,
        required this.oddsCornersOver95,
        required this.oddsCornersOver105,
        required this.oddsCornersOver115,
        required this.oddsCornersUnder75,
        required this.oddsCornersUnder85,
        required this.oddsCornersUnder95,
        required this.oddsCornersUnder105,
        required this.oddsCornersUnder115,
        required this.oddsCorners1,
        required this.oddsCornersX,
        required this.oddsCorners2,
        required this.oddsTeamToScoreFirst1,
        required this.oddsTeamToScoreFirstX,
        required this.oddsTeamToScoreFirst2,
        required this.oddsWinToNil1,
        required this.oddsWinToNil2,
        required this.odds1StHalfOver05,
        required this.odds1StHalfOver15,
        required this.odds1StHalfOver25,
        required this.odds1StHalfOver35,
        required this.odds1StHalfUnder05,
        required this.odds1StHalfUnder15,
        required this.odds1StHalfUnder25,
        required this.odds1StHalfUnder35,
        required this.odds2NdHalfOver05,
        required this.odds2NdHalfOver15,
        required this.odds2NdHalfOver25,
        required this.odds2NdHalfOver35,
        required this.odds2NdHalfUnder05,
        required this.odds2NdHalfUnder15,
        required this.odds2NdHalfUnder25,
        required this.odds2NdHalfUnder35,
        required this.oddsBtts1StHalfYes,
        required this.oddsBtts1StHalfNo,
        required this.oddsBtts2NdHalfYes,
        required this.oddsBtts2NdHalfNo,
        required this.overallGoalCount,
        required this.htGoalsTeamA,
        required this.htGoalsTeamB,
        required this.goals2HgTeamA,
        required this.goals2HgTeamB,
        required this.goalCount2Hg,
        required this.htGoalCount,
        required this.dateUnix,
        required this.winningTeam,
        required this.noHomeAway,
        required this.bttsPotential,
        required this.bttsFhgPotential,
        required this.btts2HgPotential,
        required this.goalTimingDisabled,
        required this.attendance,
        required this.cornerTimingsRecorded,
        required this.cardTimingsRecorded,
        required this.teamAFhCorners,
        required this.teamBFhCorners,
        required this.teamA2HCorners,
        required this.teamB2HCorners,
        required this.cornerFhCount,
        required this.corner2HCount,
        required this.teamAFhCards,
        required this.teamBFhCards,
        required this.teamA2HCards,
        required this.teamB2HCards,
        required this.totalFhCards,
        required this.total2HCards,
        required this.attacksRecorded,
        required this.teamADangerousAttacks,
        required this.teamBDangerousAttacks,
        required this.teamAAttacks,
        required this.teamBAttacks,
        required this.teamAXg,
        required this.teamBXg,
        required this.totalXg,
        required this.teamAPenaltiesWon,
        required this.teamBPenaltiesWon,
        required this.teamAPenaltyGoals,
        required this.teamBPenaltyGoals,
        required this.teamAPenaltyMissed,
        required this.teamBPenaltyMissed,
        required this.pensRecorded,
        required this.goalTimingsRecorded,
        required this.teamA010MinGoals,
        required this.teamB010MinGoals,
        required this.teamACorners010Min,
        required this.teamBCorners010Min,
        required this.teamACards010Min,
        required this.teamBCards010Min,
        required this.throwinsRecorded,
        required this.teamAThrowins,
        required this.teamBThrowins,
        required this.freekicksRecorded,
        required this.teamAFreekicks,
        required this.teamBFreekicks,
        required this.goalkicksRecorded,
        required this.teamAGoalkicks,
        required this.teamBGoalkicks,
        required this.o45Potential,
        required this.o35Potential,
        required this.o25Potential,
        required this.o15Potential,
        required this.o05Potential,
        required this.o15HtPotential,
        required this.o05HtPotential,
        required this.o052HPotential,
        required this.o152HPotential,
        required this.cornersPotential,
        required this.offsidesPotential,
        required this.cardsPotential,
        required this.avgPotential,
        required this.homeUrl,
        required this.homeImage,
        required this.homeName,
        required this.awayUrl,
        required this.awayImage,
        required this.awayName,
        required this.homePpg,
        required this.awayPpg,
        required this.preMatchHomePpg,
        required this.preMatchAwayPpg,
        required this.preMatchTeamAOverallPpg,
        required this.preMatchTeamBOverallPpg,
        required this.u45Potential,
        required this.u35Potential,
        required this.u25Potential,
        required this.u15Potential,
        required this.u05Potential,
        required this.cornersO85Potential,
        required this.cornersO95Potential,
        required this.cornersO105Potential,
        required this.teamAXgPrematch,
        required this.teamBXgPrematch,
        required this.totalXgPrematch,
        required this.matchUrl,
        required this.competitionId,
        required this.matchesCompletedMinimum,
        required this.homeGoalsTimings,
        required this.awayGoalsTimings,
    });

    factory Datum.fromJson(Map<String, dynamic> json) => Datum(
        id: json["id"],
        homeId: json["homeID"],
        awayId: json["awayID"],
        season: json["season"],
        status: statusValues.map[json["status"]]!,
        roundId: json["roundID"],
        gameWeek: json["game_week"],
        revisedGameWeek: json["revised_game_week"],
        homeGoals: goalsValues.map[json["homeGoals"]]!,
        awayGoals: goalsValues.map[json["awayGoals"]]!,
        homeGoalCount: json["homeGoalCount"],
        awayGoalCount: json["awayGoalCount"],
        totalGoalCount: json["totalGoalCount"],
        teamACorners: json["team_a_corners"],
        teamBCorners: json["team_b_corners"],
        totalCornerCount: json["totalCornerCount"],
        teamAOffsides: json["team_a_offsides"],
        teamBOffsides: json["team_b_offsides"],
        teamAYellowCards: json["team_a_yellow_cards"],
        teamBYellowCards: json["team_b_yellow_cards"],
        teamARedCards: json["team_a_red_cards"],
        teamBRedCards: json["team_b_red_cards"],
        teamAShotsOnTarget: json["team_a_shotsOnTarget"],
        teamBShotsOnTarget: json["team_b_shotsOnTarget"],
        teamAShotsOffTarget: json["team_a_shotsOffTarget"],
        teamBShotsOffTarget: json["team_b_shotsOffTarget"],
        teamAShots: json["team_a_shots"],
        teamBShots: json["team_b_shots"],
        teamAFouls: json["team_a_fouls"],
        teamBFouls: json["team_b_fouls"],
        teamAPossession: json["team_a_possession"],
        teamBPossession: json["team_b_possession"],
        refereeId: json["refereeID"],
        coachAId: json["coach_a_ID"],
        coachBId: json["coach_b_ID"],
        stadiumName: json["stadium_name"],
        stadiumLocation: json["stadium_location"],
        teamACardsNum: json["team_a_cards_num"],
        teamBCardsNum: json["team_b_cards_num"],
        oddsFt1: json["odds_ft_1"]?.toDouble(),
        oddsFtX: json["odds_ft_x"]?.toDouble(),
        oddsFt2: json["odds_ft_2"]?.toDouble(),
        oddsFtOver05: json["odds_ft_over05"]?.toDouble(),
        oddsFtOver15: json["odds_ft_over15"]?.toDouble(),
        oddsFtOver25: json["odds_ft_over25"]?.toDouble(),
        oddsFtOver35: json["odds_ft_over35"]?.toDouble(),
        oddsFtOver45: json["odds_ft_over45"]?.toDouble(),
        oddsFtUnder05: json["odds_ft_under05"]?.toDouble(),
        oddsFtUnder15: json["odds_ft_under15"]?.toDouble(),
        oddsFtUnder25: json["odds_ft_under25"]?.toDouble(),
        oddsFtUnder35: json["odds_ft_under35"]?.toDouble(),
        oddsFtUnder45: json["odds_ft_under45"]?.toDouble(),
        oddsBttsYes: json["odds_btts_yes"]?.toDouble(),
        oddsBttsNo: json["odds_btts_no"]?.toDouble(),
        oddsTeamACsYes: json["odds_team_a_cs_yes"]?.toDouble(),
        oddsTeamACsNo: json["odds_team_a_cs_no"]?.toDouble(),
        oddsTeamBCsYes: json["odds_team_b_cs_yes"]?.toDouble(),
        oddsTeamBCsNo: json["odds_team_b_cs_no"]?.toDouble(),
        oddsDoublechance1X: json["odds_doublechance_1x"]?.toDouble(),
        oddsDoublechance12: json["odds_doublechance_12"]?.toDouble(),
        oddsDoublechanceX2: json["odds_doublechance_x2"]?.toDouble(),
        odds1StHalfResult1: json["odds_1st_half_result_1"]?.toDouble(),
        odds1StHalfResultX: json["odds_1st_half_result_x"]?.toDouble(),
        odds1StHalfResult2: json["odds_1st_half_result_2"]?.toDouble(),
        odds2NdHalfResult1: json["odds_2nd_half_result_1"]?.toDouble(),
        odds2NdHalfResultX: json["odds_2nd_half_result_x"]?.toDouble(),
        odds2NdHalfResult2: json["odds_2nd_half_result_2"]?.toDouble(),
        oddsDnb1: json["odds_dnb_1"]?.toDouble(),
        oddsDnb2: json["odds_dnb_2"]?.toDouble(),
        oddsCornersOver75: json["odds_corners_over_75"]?.toDouble(),
        oddsCornersOver85: json["odds_corners_over_85"]?.toDouble(),
        oddsCornersOver95: json["odds_corners_over_95"]?.toDouble(),
        oddsCornersOver105: json["odds_corners_over_105"]?.toDouble(),
        oddsCornersOver115: json["odds_corners_over_115"]?.toDouble(),
        oddsCornersUnder75: json["odds_corners_under_75"]?.toDouble(),
        oddsCornersUnder85: json["odds_corners_under_85"]?.toDouble(),
        oddsCornersUnder95: json["odds_corners_under_95"]?.toDouble(),
        oddsCornersUnder105: json["odds_corners_under_105"]?.toDouble(),
        oddsCornersUnder115: json["odds_corners_under_115"]?.toDouble(),
        oddsCorners1: json["odds_corners_1"]?.toDouble(),
        oddsCornersX: json["odds_corners_x"]?.toDouble(),
        oddsCorners2: json["odds_corners_2"]?.toDouble(),
        oddsTeamToScoreFirst1: json["odds_team_to_score_first_1"]?.toDouble(),
        oddsTeamToScoreFirstX: json["odds_team_to_score_first_x"]?.toDouble(),
        oddsTeamToScoreFirst2: json["odds_team_to_score_first_2"]?.toDouble(),
        oddsWinToNil1: json["odds_win_to_nil_1"]?.toDouble(),
        oddsWinToNil2: json["odds_win_to_nil_2"]?.toDouble(),
        odds1StHalfOver05: json["odds_1st_half_over05"]?.toDouble(),
        odds1StHalfOver15: json["odds_1st_half_over15"]?.toDouble(),
        odds1StHalfOver25: json["odds_1st_half_over25"]?.toDouble(),
        odds1StHalfOver35: json["odds_1st_half_over35"]?.toDouble(),
        odds1StHalfUnder05: json["odds_1st_half_under05"]?.toDouble(),
        odds1StHalfUnder15: json["odds_1st_half_under15"]?.toDouble(),
        odds1StHalfUnder25: json["odds_1st_half_under25"]?.toDouble(),
        odds1StHalfUnder35: json["odds_1st_half_under35"]?.toDouble(),
        odds2NdHalfOver05: json["odds_2nd_half_over05"]?.toDouble(),
        odds2NdHalfOver15: json["odds_2nd_half_over15"]?.toDouble(),
        odds2NdHalfOver25: json["odds_2nd_half_over25"]?.toDouble(),
        odds2NdHalfOver35: json["odds_2nd_half_over35"]?.toDouble(),
        odds2NdHalfUnder05: json["odds_2nd_half_under05"]?.toDouble(),
        odds2NdHalfUnder15: json["odds_2nd_half_under15"]?.toDouble(),
        odds2NdHalfUnder25: json["odds_2nd_half_under25"]?.toDouble(),
        odds2NdHalfUnder35: json["odds_2nd_half_under35"]?.toDouble(),
        oddsBtts1StHalfYes: json["odds_btts_1st_half_yes"],
        oddsBtts1StHalfNo: json["odds_btts_1st_half_no"],
        oddsBtts2NdHalfYes: json["odds_btts_2nd_half_yes"],
        oddsBtts2NdHalfNo: json["odds_btts_2nd_half_no"],
        overallGoalCount: json["overallGoalCount"],
        htGoalsTeamA: json["ht_goals_team_a"],
        htGoalsTeamB: json["ht_goals_team_b"],
        goals2HgTeamA: json["goals_2hg_team_a"],
        goals2HgTeamB: json["goals_2hg_team_b"],
        goalCount2Hg: json["GoalCount_2hg"],
        htGoalCount: json["HTGoalCount"],
        dateUnix: json["date_unix"],
        winningTeam: json["winningTeam"],
        noHomeAway: json["no_home_away"],
        bttsPotential: json["btts_potential"],
        bttsFhgPotential: json["btts_fhg_potential"],
        btts2HgPotential: json["btts_2hg_potential"],
        goalTimingDisabled: json["goalTimingDisabled"],
        attendance: json["attendance"],
        cornerTimingsRecorded: json["corner_timings_recorded"],
        cardTimingsRecorded: json["card_timings_recorded"],
        teamAFhCorners: json["team_a_fh_corners"],
        teamBFhCorners: json["team_b_fh_corners"],
        teamA2HCorners: json["team_a_2h_corners"],
        teamB2HCorners: json["team_b_2h_corners"],
        cornerFhCount: json["corner_fh_count"],
        corner2HCount: json["corner_2h_count"],
        teamAFhCards: json["team_a_fh_cards"],
        teamBFhCards: json["team_b_fh_cards"],
        teamA2HCards: json["team_a_2h_cards"],
        teamB2HCards: json["team_b_2h_cards"],
        totalFhCards: json["total_fh_cards"],
        total2HCards: json["total_2h_cards"],
        attacksRecorded: json["attacks_recorded"],
        teamADangerousAttacks: json["team_a_dangerous_attacks"],
        teamBDangerousAttacks: json["team_b_dangerous_attacks"],
        teamAAttacks: json["team_a_attacks"],
        teamBAttacks: json["team_b_attacks"],
        teamAXg: json["team_a_xg"],
        teamBXg: json["team_b_xg"],
        totalXg: json["total_xg"],
        teamAPenaltiesWon: json["team_a_penalties_won"],
        teamBPenaltiesWon: json["team_b_penalties_won"],
        teamAPenaltyGoals: json["team_a_penalty_goals"],
        teamBPenaltyGoals: json["team_b_penalty_goals"],
        teamAPenaltyMissed: json["team_a_penalty_missed"],
        teamBPenaltyMissed: json["team_b_penalty_missed"],
        pensRecorded: json["pens_recorded"],
        goalTimingsRecorded: json["goal_timings_recorded"],
        teamA010MinGoals: json["team_a_0_10_min_goals"],
        teamB010MinGoals: json["team_b_0_10_min_goals"],
        teamACorners010Min: json["team_a_corners_0_10_min"],
        teamBCorners010Min: json["team_b_corners_0_10_min"],
        teamACards010Min: json["team_a_cards_0_10_min"],
        teamBCards010Min: json["team_b_cards_0_10_min"],
        throwinsRecorded: json["throwins_recorded"],
        teamAThrowins: json["team_a_throwins"],
        teamBThrowins: json["team_b_throwins"],
        freekicksRecorded: json["freekicks_recorded"],
        teamAFreekicks: json["team_a_freekicks"],
        teamBFreekicks: json["team_b_freekicks"],
        goalkicksRecorded: json["goalkicks_recorded"],
        teamAGoalkicks: json["team_a_goalkicks"],
        teamBGoalkicks: json["team_b_goalkicks"],
        o45Potential: json["o45_potential"],
        o35Potential: json["o35_potential"],
        o25Potential: json["o25_potential"],
        o15Potential: json["o15_potential"],
        o05Potential: json["o05_potential"],
        o15HtPotential: json["o15HT_potential"],
        o05HtPotential: json["o05HT_potential"],
        o052HPotential: json["o05_2H_potential"],
        o152HPotential: json["o15_2H_potential"],
        cornersPotential: json["corners_potential"]?.toDouble(),
        offsidesPotential: json["offsides_potential"]?.toDouble(),
        cardsPotential: json["cards_potential"]?.toDouble(),
        avgPotential: json["avg_potential"]?.toDouble(),
        homeUrl: json["home_url"],
        homeImage: json["home_image"],
        homeName: json["home_name"],
        awayUrl: json["away_url"],
        awayImage: json["away_image"],
        awayName: json["away_name"],
        homePpg: json["home_ppg"]?.toDouble(),
        awayPpg: json["away_ppg"]?.toDouble(),
        preMatchHomePpg: json["pre_match_home_ppg"]?.toDouble(),
        preMatchAwayPpg: json["pre_match_away_ppg"]?.toDouble(),
        preMatchTeamAOverallPpg: json["pre_match_teamA_overall_ppg"]?.toDouble(),
        preMatchTeamBOverallPpg: json["pre_match_teamB_overall_ppg"]?.toDouble(),
        u45Potential: json["u45_potential"],
        u35Potential: json["u35_potential"],
        u25Potential: json["u25_potential"],
        u15Potential: json["u15_potential"],
        u05Potential: json["u05_potential"],
        cornersO85Potential: json["corners_o85_potential"],
        cornersO95Potential: json["corners_o95_potential"],
        cornersO105Potential: json["corners_o105_potential"],
        teamAXgPrematch: json["team_a_xg_prematch"]?.toDouble(),
        teamBXgPrematch: json["team_b_xg_prematch"]?.toDouble(),
        totalXgPrematch: json["total_xg_prematch"]?.toDouble(),
        matchUrl: json["match_url"],
        competitionId: json["competition_id"],
        matchesCompletedMinimum: json["matches_completed_minimum"],
        homeGoalsTimings: List<dynamic>.from(json["homeGoals_timings"].map((x) => x)),
        awayGoalsTimings: List<dynamic>.from(json["awayGoals_timings"].map((x) => x)),
    );

    Map<String, dynamic> toJson() => {
        "id": id,
        "homeID": homeId,
        "awayID": awayId,
        "season": season,
        "status": statusValues.reverse[status],
        "roundID": roundId,
        "game_week": gameWeek,
        "revised_game_week": revisedGameWeek,
        "homeGoals": goalsValues.reverse[homeGoals],
        "awayGoals": goalsValues.reverse[awayGoals],
        "homeGoalCount": homeGoalCount,
        "awayGoalCount": awayGoalCount,
        "totalGoalCount": totalGoalCount,
        "team_a_corners": teamACorners,
        "team_b_corners": teamBCorners,
        "totalCornerCount": totalCornerCount,
        "team_a_offsides": teamAOffsides,
        "team_b_offsides": teamBOffsides,
        "team_a_yellow_cards": teamAYellowCards,
        "team_b_yellow_cards": teamBYellowCards,
        "team_a_red_cards": teamARedCards,
        "team_b_red_cards": teamBRedCards,
        "team_a_shotsOnTarget": teamAShotsOnTarget,
        "team_b_shotsOnTarget": teamBShotsOnTarget,
        "team_a_shotsOffTarget": teamAShotsOffTarget,
        "team_b_shotsOffTarget": teamBShotsOffTarget,
        "team_a_shots": teamAShots,
        "team_b_shots": teamBShots,
        "team_a_fouls": teamAFouls,
        "team_b_fouls": teamBFouls,
        "team_a_possession": teamAPossession,
        "team_b_possession": teamBPossession,
        "refereeID": refereeId,
        "coach_a_ID": coachAId,
        "coach_b_ID": coachBId,
        "stadium_name": stadiumName,
        "stadium_location": stadiumLocation,
        "team_a_cards_num": teamACardsNum,
        "team_b_cards_num": teamBCardsNum,
        "odds_ft_1": oddsFt1,
        "odds_ft_x": oddsFtX,
        "odds_ft_2": oddsFt2,
        "odds_ft_over05": oddsFtOver05,
        "odds_ft_over15": oddsFtOver15,
        "odds_ft_over25": oddsFtOver25,
        "odds_ft_over35": oddsFtOver35,
        "odds_ft_over45": oddsFtOver45,
        "odds_ft_under05": oddsFtUnder05,
        "odds_ft_under15": oddsFtUnder15,
        "odds_ft_under25": oddsFtUnder25,
        "odds_ft_under35": oddsFtUnder35,
        "odds_ft_under45": oddsFtUnder45,
        "odds_btts_yes": oddsBttsYes,
        "odds_btts_no": oddsBttsNo,
        "odds_team_a_cs_yes": oddsTeamACsYes,
        "odds_team_a_cs_no": oddsTeamACsNo,
        "odds_team_b_cs_yes": oddsTeamBCsYes,
        "odds_team_b_cs_no": oddsTeamBCsNo,
        "odds_doublechance_1x": oddsDoublechance1X,
        "odds_doublechance_12": oddsDoublechance12,
        "odds_doublechance_x2": oddsDoublechanceX2,
        "odds_1st_half_result_1": odds1StHalfResult1,
        "odds_1st_half_result_x": odds1StHalfResultX,
        "odds_1st_half_result_2": odds1StHalfResult2,
        "odds_2nd_half_result_1": odds2NdHalfResult1,
        "odds_2nd_half_result_x": odds2NdHalfResultX,
        "odds_2nd_half_result_2": odds2NdHalfResult2,
        "odds_dnb_1": oddsDnb1,
        "odds_dnb_2": oddsDnb2,
        "odds_corners_over_75": oddsCornersOver75,
        "odds_corners_over_85": oddsCornersOver85,
        "odds_corners_over_95": oddsCornersOver95,
        "odds_corners_over_105": oddsCornersOver105,
        "odds_corners_over_115": oddsCornersOver115,
        "odds_corners_under_75": oddsCornersUnder75,
        "odds_corners_under_85": oddsCornersUnder85,
        "odds_corners_under_95": oddsCornersUnder95,
        "odds_corners_under_105": oddsCornersUnder105,
        "odds_corners_under_115": oddsCornersUnder115,
        "odds_corners_1": oddsCorners1,
        "odds_corners_x": oddsCornersX,
        "odds_corners_2": oddsCorners2,
        "odds_team_to_score_first_1": oddsTeamToScoreFirst1,
        "odds_team_to_score_first_x": oddsTeamToScoreFirstX,
        "odds_team_to_score_first_2": oddsTeamToScoreFirst2,
        "odds_win_to_nil_1": oddsWinToNil1,
        "odds_win_to_nil_2": oddsWinToNil2,
        "odds_1st_half_over05": odds1StHalfOver05,
        "odds_1st_half_over15": odds1StHalfOver15,
        "odds_1st_half_over25": odds1StHalfOver25,
        "odds_1st_half_over35": odds1StHalfOver35,
        "odds_1st_half_under05": odds1StHalfUnder05,
        "odds_1st_half_under15": odds1StHalfUnder15,
        "odds_1st_half_under25": odds1StHalfUnder25,
        "odds_1st_half_under35": odds1StHalfUnder35,
        "odds_2nd_half_over05": odds2NdHalfOver05,
        "odds_2nd_half_over15": odds2NdHalfOver15,
        "odds_2nd_half_over25": odds2NdHalfOver25,
        "odds_2nd_half_over35": odds2NdHalfOver35,
        "odds_2nd_half_under05": odds2NdHalfUnder05,
        "odds_2nd_half_under15": odds2NdHalfUnder15,
        "odds_2nd_half_under25": odds2NdHalfUnder25,
        "odds_2nd_half_under35": odds2NdHalfUnder35,
        "odds_btts_1st_half_yes": oddsBtts1StHalfYes,
        "odds_btts_1st_half_no": oddsBtts1StHalfNo,
        "odds_btts_2nd_half_yes": oddsBtts2NdHalfYes,
        "odds_btts_2nd_half_no": oddsBtts2NdHalfNo,
        "overallGoalCount": overallGoalCount,
        "ht_goals_team_a": htGoalsTeamA,
        "ht_goals_team_b": htGoalsTeamB,
        "goals_2hg_team_a": goals2HgTeamA,
        "goals_2hg_team_b": goals2HgTeamB,
        "GoalCount_2hg": goalCount2Hg,
        "HTGoalCount": htGoalCount,
        "date_unix": dateUnix,
        "winningTeam": winningTeam,
        "no_home_away": noHomeAway,
        "btts_potential": bttsPotential,
        "btts_fhg_potential": bttsFhgPotential,
        "btts_2hg_potential": btts2HgPotential,
        "goalTimingDisabled": goalTimingDisabled,
        "attendance": attendance,
        "corner_timings_recorded": cornerTimingsRecorded,
        "card_timings_recorded": cardTimingsRecorded,
        "team_a_fh_corners": teamAFhCorners,
        "team_b_fh_corners": teamBFhCorners,
        "team_a_2h_corners": teamA2HCorners,
        "team_b_2h_corners": teamB2HCorners,
        "corner_fh_count": cornerFhCount,
        "corner_2h_count": corner2HCount,
        "team_a_fh_cards": teamAFhCards,
        "team_b_fh_cards": teamBFhCards,
        "team_a_2h_cards": teamA2HCards,
        "team_b_2h_cards": teamB2HCards,
        "total_fh_cards": totalFhCards,
        "total_2h_cards": total2HCards,
        "attacks_recorded": attacksRecorded,
        "team_a_dangerous_attacks": teamADangerousAttacks,
        "team_b_dangerous_attacks": teamBDangerousAttacks,
        "team_a_attacks": teamAAttacks,
        "team_b_attacks": teamBAttacks,
        "team_a_xg": teamAXg,
        "team_b_xg": teamBXg,
        "total_xg": totalXg,
        "team_a_penalties_won": teamAPenaltiesWon,
        "team_b_penalties_won": teamBPenaltiesWon,
        "team_a_penalty_goals": teamAPenaltyGoals,
        "team_b_penalty_goals": teamBPenaltyGoals,
        "team_a_penalty_missed": teamAPenaltyMissed,
        "team_b_penalty_missed": teamBPenaltyMissed,
        "pens_recorded": pensRecorded,
        "goal_timings_recorded": goalTimingsRecorded,
        "team_a_0_10_min_goals": teamA010MinGoals,
        "team_b_0_10_min_goals": teamB010MinGoals,
        "team_a_corners_0_10_min": teamACorners010Min,
        "team_b_corners_0_10_min": teamBCorners010Min,
        "team_a_cards_0_10_min": teamACards010Min,
        "team_b_cards_0_10_min": teamBCards010Min,
        "throwins_recorded": throwinsRecorded,
        "team_a_throwins": teamAThrowins,
        "team_b_throwins": teamBThrowins,
        "freekicks_recorded": freekicksRecorded,
        "team_a_freekicks": teamAFreekicks,
        "team_b_freekicks": teamBFreekicks,
        "goalkicks_recorded": goalkicksRecorded,
        "team_a_goalkicks": teamAGoalkicks,
        "team_b_goalkicks": teamBGoalkicks,
        "o45_potential": o45Potential,
        "o35_potential": o35Potential,
        "o25_potential": o25Potential,
        "o15_potential": o15Potential,
        "o05_potential": o05Potential,
        "o15HT_potential": o15HtPotential,
        "o05HT_potential": o05HtPotential,
        "o05_2H_potential": o052HPotential,
        "o15_2H_potential": o152HPotential,
        "corners_potential": cornersPotential,
        "offsides_potential": offsidesPotential,
        "cards_potential": cardsPotential,
        "avg_potential": avgPotential,
        "home_url": homeUrl,
        "home_image": homeImage,
        "home_name": homeName,
        "away_url": awayUrl,
        "away_image": awayImage,
        "away_name": awayName,
        "home_ppg": homePpg,
        "away_ppg": awayPpg,
        "pre_match_home_ppg": preMatchHomePpg,
        "pre_match_away_ppg": preMatchAwayPpg,
        "pre_match_teamA_overall_ppg": preMatchTeamAOverallPpg,
        "pre_match_teamB_overall_ppg": preMatchTeamBOverallPpg,
        "u45_potential": u45Potential,
        "u35_potential": u35Potential,
        "u25_potential": u25Potential,
        "u15_potential": u15Potential,
        "u05_potential": u05Potential,
        "corners_o85_potential": cornersO85Potential,
        "corners_o95_potential": cornersO95Potential,
        "corners_o105_potential": cornersO105Potential,
        "team_a_xg_prematch": teamAXgPrematch,
        "team_b_xg_prematch": teamBXgPrematch,
        "total_xg_prematch": totalXgPrematch,
        "match_url": matchUrl,
        "competition_id": competitionId,
        "matches_completed_minimum": matchesCompletedMinimum,
        "homeGoals_timings": List<dynamic>.from(homeGoalsTimings.map((x) => x)),
        "awayGoals_timings": List<dynamic>.from(awayGoalsTimings.map((x) => x)),
    };
}

enum Goals {
    EMPTY
}

final goalsValues = EnumValues({
    "[]": Goals.EMPTY
});

enum Status {
    INCOMPLETE,
    SUSPENDED
}

final statusValues = EnumValues({
    "incomplete": Status.INCOMPLETE,
    "suspended": Status.SUSPENDED
});

class Metadata {
    String requestLimit;
    String requestRemaining;
    String requestResetMessage;

    Metadata({
        required this.requestLimit,
        required this.requestRemaining,
        required this.requestResetMessage,
    });

    factory Metadata.fromJson(Map<String, dynamic> json) => Metadata(
        requestLimit: json["request_limit"],
        requestRemaining: json["request_remaining"],
        requestResetMessage: json["request_reset_message"],
    );

    Map<String, dynamic> toJson() => {
        "request_limit": requestLimit,
        "request_remaining": requestRemaining,
        "request_reset_message": requestResetMessage,
    };
}

class Pager {
    int currentPage;
    int maxPage;
    int resultsPerPage;
    int totalResults;

    Pager({
        required this.currentPage,
        required this.maxPage,
        required this.resultsPerPage,
        required this.totalResults,
    });

    factory Pager.fromJson(Map<String, dynamic> json) => Pager(
        currentPage: json["current_page"],
        maxPage: json["max_page"],
        resultsPerPage: json["results_per_page"],
        totalResults: json["total_results"],
    );

    Map<String, dynamic> toJson() => {
        "current_page": currentPage,
        "max_page": maxPage,
        "results_per_page": resultsPerPage,
        "total_results": totalResults,
    };
}

class EnumValues<T> {
    Map<String, T> map;
    late Map<T, String> reverseMap;

    EnumValues(this.map);

    Map<T, String> get reverse {
            reverseMap = map.map((k, v) => MapEntry(v, k));
            return reverseMap;
    }
}
