// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpS7Mhsqq8tVbSVdW2UTlQBH517kDrf9s',
    appId: '1:949319954406:web:c1b4d8664b72155a03b027',
    messagingSenderId: '949319954406',
    projectId: 'game-grid-dcc11',
    authDomain: 'game-grid-dcc11.firebaseapp.com',
    storageBucket: 'game-grid-dcc11.firebasestorage.app',
    measurementId: 'G-W5Y29R0HBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlJfImpW6c_lhcGJSKrlpQNNROqBZBtqI',
    appId: '1:949319954406:android:d1a33802e3ccbe7303b027',
    messagingSenderId: '949319954406',
    projectId: 'game-grid-dcc11',
    storageBucket: 'game-grid-dcc11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvfhVZXnJ-llJJn21mps8p3Ik4m1WwtS0',
    appId: '1:949319954406:ios:4b8083816bfd7b6603b027',
    messagingSenderId: '949319954406',
    projectId: 'game-grid-dcc11',
    storageBucket: 'game-grid-dcc11.firebasestorage.app',
    iosBundleId: 'com.example.gameGrid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvfhVZXnJ-llJJn21mps8p3Ik4m1WwtS0',
    appId: '1:949319954406:ios:4b8083816bfd7b6603b027',
    messagingSenderId: '949319954406',
    projectId: 'game-grid-dcc11',
    storageBucket: 'game-grid-dcc11.firebasestorage.app',
    iosBundleId: 'com.example.gameGrid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpS7Mhsqq8tVbSVdW2UTlQBH517kDrf9s',
    appId: '1:949319954406:web:dec75bb89251978903b027',
    messagingSenderId: '949319954406',
    projectId: 'game-grid-dcc11',
    authDomain: 'game-grid-dcc11.firebaseapp.com',
    storageBucket: 'game-grid-dcc11.firebasestorage.app',
    measurementId: 'G-JSCF78031J',
  );
}
